dist: xenial
language: python

python:
  - 3.6
  - 3.7
  - 3.8

env:
  - DJANGO_VERSION: "'Django==1.11.*'"
  - DJANGO_VERSION: "'Django==2.2.*'"
  - DJANGO_VERSION: "'Django==3.1.*'"

before_install:
  - pip freeze | xargs pip uninstall -y
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source "$HOME/.poetry/env"

install:
  - poetry install
  - pip install -U "$DJANGO_VERSION"

script:
  - poetry run flake8 .
  - poetry run mypy split_settings
  - poetry run pytest
  - poetry run doc8 -q docs
  - poetry check
  - poetry run pip check
  # Ignoring sphinx@2 security issue for now, see:
  # https://github.com/miyakogi/m2r/issues/51
  - poetry run safety check --full-report -i 38330

after_success:
  - pip install coveralls
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: change
